package com.homeboy.app.ui

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.ui.graphics.vector.ImageVector

/**
 * Curated set of free Material (outlined) icons users can attach to a tag.
 * Shown by default (no search query). The tag's `icon` field stores the lowercase key.
 */
val TAG_ICONS: List<Pair<String, ImageVector>> = listOf(
    "home" to Icons.Outlined.Home,
    "apartment" to Icons.Outlined.Apartment,
    "cottage" to Icons.Outlined.Cottage,
    "garage" to Icons.Outlined.Garage,
    "store" to Icons.Outlined.Store,
    "warehouse" to Icons.Outlined.Warehouse,
    "bed" to Icons.Outlined.Bed,
    "couch" to Icons.Outlined.Weekend,
    "chair" to Icons.Outlined.Chair,
    "kitchen" to Icons.Outlined.Kitchen,
    "microwave" to Icons.Outlined.Microwave,
    "bathtub" to Icons.Outlined.Bathtub,
    "star" to Icons.Outlined.Star,
    "favorite" to Icons.Outlined.Favorite,
    "bookmark" to Icons.Outlined.Bookmark,
    "flag" to Icons.Outlined.Flag,
    "label" to Icons.Outlined.Label,
    "category" to Icons.Outlined.Category,
    "box" to Icons.Outlined.Inventory2,
    "work" to Icons.Outlined.Work,
    "school" to Icons.Outlined.School,
    "book" to Icons.Outlined.Book,
    "menubook" to Icons.Outlined.MenuBook,
    "science" to Icons.Outlined.Science,
    "shopping" to Icons.Outlined.ShoppingCart,
    "gift" to Icons.Outlined.CardGiftcard,
    "cake" to Icons.Outlined.Cake,
    "food" to Icons.Outlined.Restaurant,
    "coffee" to Icons.Outlined.LocalCafe,
    "build" to Icons.Outlined.Build,
    "hardware" to Icons.Outlined.Hardware,
    "tools" to Icons.Outlined.HomeRepairService,
    "computer" to Icons.Outlined.Computer,
    "laptop" to Icons.Outlined.Laptop,
    "phone" to Icons.Outlined.Smartphone,
    "tv" to Icons.Outlined.Tv,
    "watch" to Icons.Outlined.Watch,
    "camera" to Icons.Outlined.CameraAlt,
    "headphones" to Icons.Outlined.Headphones,
    "music" to Icons.Outlined.MusicNote,
    "games" to Icons.Outlined.SportsEsports,
    "toys" to Icons.Outlined.Toys,
    "fitness" to Icons.Outlined.FitnessCenter,
    "palette" to Icons.Outlined.Palette,
    "brush" to Icons.Outlined.Brush,
    "car" to Icons.Outlined.DirectionsCar,
    "flight" to Icons.Outlined.Flight,
    "backpack" to Icons.Outlined.Backpack,
    "pets" to Icons.Outlined.Pets,
    "flower" to Icons.Outlined.LocalFlorist,
    "park" to Icons.Outlined.Park,
    "beach" to Icons.Outlined.BeachAccess,
    "cold" to Icons.Outlined.AcUnit,
    "light" to Icons.Outlined.Lightbulb,
    "power" to Icons.Outlined.Bolt,
    "key" to Icons.Outlined.Key,
    "lock" to Icons.Outlined.Lock,
    "medical" to Icons.Outlined.MedicalServices,
    "spa" to Icons.Outlined.Spa,
    "clothes" to Icons.Outlined.Checkroom,
    "diamond" to Icons.Outlined.Diamond,
    "settings" to Icons.Outlined.Settings
)

/**
 * Extended icon catalog — superset of TAG_ICONS, searched when the user types in the icon search
 * bar. Covers the same icons shown on mui.com/material-ui/material-icons (Material Design Icons).
 */
val ALL_MATERIAL_ICONS: List<Pair<String, ImageVector>> = TAG_ICONS + listOf(
    // People & Identity
    "person" to Icons.Outlined.Person,
    "group" to Icons.Outlined.Group,
    "people" to Icons.Outlined.People,
    "person_add" to Icons.Outlined.PersonAdd,
    "account" to Icons.Outlined.AccountCircle,
    "badge" to Icons.Outlined.Badge,
    "fingerprint" to Icons.Outlined.Fingerprint,
    "face" to Icons.Outlined.Face,
    "contacts" to Icons.Outlined.Contacts,

    // Communication
    "email" to Icons.Outlined.Email,
    "mail" to Icons.Outlined.Mail,
    "chat" to Icons.Outlined.Chat,
    "message" to Icons.Outlined.Message,
    "forum" to Icons.Outlined.Forum,
    "call" to Icons.Outlined.Call,
    "mic" to Icons.Outlined.Mic,
    "sms" to Icons.Outlined.Sms,
    "send" to Icons.Outlined.Send,
    "share" to Icons.Outlined.Share,

    // Navigation & Maps
    "map" to Icons.Outlined.Map,
    "pin" to Icons.Outlined.PinDrop,
    "directions" to Icons.Outlined.Directions,
    "explore" to Icons.Outlined.Explore,
    "navigation" to Icons.Outlined.Navigation,
    "near_me" to Icons.Outlined.NearMe,
    "gps" to Icons.Outlined.GpsFixed,
    "room" to Icons.Outlined.Room,

    // Transport
    "bus" to Icons.Outlined.DirectionsBus,
    "bike" to Icons.Outlined.DirectionsBike,
    "run" to Icons.Outlined.DirectionsRun,
    "walk" to Icons.Outlined.DirectionsWalk,
    "train" to Icons.Outlined.DirectionsRailway,
    "subway" to Icons.Outlined.Subway,
    "ship" to Icons.Outlined.DirectionsBoat,
    "truck" to Icons.Outlined.LocalShipping,
    "taxi" to Icons.Outlined.LocalTaxi,
    "two_wheeler" to Icons.Outlined.TwoWheeler,
    "electric_car" to Icons.Outlined.ElectricCar,
    "electric_scooter" to Icons.Outlined.ElectricScooter,
    "ev_station" to Icons.Outlined.EvStation,
    "airport_shuttle" to Icons.Outlined.AirportShuttle,

    // Finance
    "money" to Icons.Outlined.MonetizationOn,
    "wallet" to Icons.Outlined.AccountBalanceWallet,
    "bank" to Icons.Outlined.AccountBalance,
    "credit_card" to Icons.Outlined.CreditCard,
    "receipt" to Icons.Outlined.Receipt,
    "savings" to Icons.Outlined.Savings,
    "price_tag" to Icons.Outlined.LocalOffer,
    "attach_money" to Icons.Outlined.AttachMoney,

    // Health & Medical
    "medication" to Icons.Outlined.Medication,
    "healing" to Icons.Outlined.Healing,
    "emergency" to Icons.Outlined.Emergency,

    // Nature & Plants
    "nature" to Icons.Outlined.Nature,
    "grass" to Icons.Outlined.Grass,
    "yard" to Icons.Outlined.Yard,

    // Food & Drink
    "local_bar" to Icons.Outlined.LocalBar,
    "icecream" to Icons.Outlined.Icecream,
    "fastfood" to Icons.Outlined.Fastfood,
    "wine" to Icons.Outlined.WineBar,
    "blender" to Icons.Outlined.Blender,
    "cookie" to Icons.Outlined.Cookie,
    "bakery" to Icons.Outlined.BakeryDining,
    "breakfast" to Icons.Outlined.FreeBreakfast,
    "lunch" to Icons.Outlined.LunchDining,
    "outdoor_grill" to Icons.Outlined.OutdoorGrill,

    // Home & Appliances
    "shower" to Icons.Outlined.Shower,
    "iron" to Icons.Outlined.Iron,
    "dryer" to Icons.Outlined.Dryer,
    "thermostat" to Icons.Outlined.Thermostat,
    "fireplace" to Icons.Outlined.Fireplace,
    "roofing" to Icons.Outlined.Roofing,
    "stairs" to Icons.Outlined.Stairs,
    "window" to Icons.Outlined.Window,
    "door" to Icons.Outlined.DoorFront,
    "fence" to Icons.Outlined.Fence,
    "deck" to Icons.Outlined.Deck,
    "lamp" to Icons.Outlined.Lamp,
    "living" to Icons.Outlined.Living,
    "foundation" to Icons.Outlined.Foundation,
    "cabin" to Icons.Outlined.Cabin,
    "cleaning" to Icons.Outlined.CleaningServices,
    "plumbing" to Icons.Outlined.Plumbing,
    "electrical" to Icons.Outlined.ElectricalServices,
    "outlet" to Icons.Outlined.Outlet,
    "chair_alt" to Icons.Outlined.ChairAlt,
    "local_fire" to Icons.Outlined.LocalFireDepartment,
    "smoke_free" to Icons.Outlined.SmokeFree,

    // Tech & Devices
    "memory" to Icons.Outlined.Memory,
    "storage" to Icons.Outlined.Storage,
    "wifi" to Icons.Outlined.Wifi,
    "bluetooth" to Icons.Outlined.Bluetooth,
    "cast" to Icons.Outlined.Cast,
    "monitor" to Icons.Outlined.Monitor,
    "speaker" to Icons.Outlined.Speaker,
    "tablet" to Icons.Outlined.Tablet,
    "router" to Icons.Outlined.Router,
    "usb" to Icons.Outlined.Usb,
    "keyboard" to Icons.Outlined.Keyboard,
    "mouse" to Icons.Outlined.Mouse,
    "headset" to Icons.Outlined.Headset,
    "qr_code" to Icons.Outlined.QrCode,
    "nfc" to Icons.Outlined.Nfc,
    "electric_bolt" to Icons.Outlined.ElectricBolt,
    "solar_power" to Icons.Outlined.SolarPower,
    "energy_leaf" to Icons.Outlined.EnergySavingsLeaf,

    // Construction & Maintenance
    "construction" to Icons.Outlined.Construction,

    // Documents & Files
    "description" to Icons.Outlined.Description,
    "folder" to Icons.Outlined.Folder,
    "folder_open" to Icons.Outlined.FolderOpen,
    "cloud" to Icons.Outlined.Cloud,
    "cloud_download" to Icons.Outlined.CloudDownload,
    "cloud_upload" to Icons.Outlined.CloudUpload,
    "save" to Icons.Outlined.Save,
    "print" to Icons.Outlined.Print,
    "link" to Icons.Outlined.Link,
    "attach" to Icons.Outlined.AttachFile,
    "note" to Icons.Outlined.Note,
    "notes" to Icons.Outlined.Notes,
    "article" to Icons.Outlined.Article,
    "topic" to Icons.Outlined.Topic,
    "download" to Icons.Outlined.Download,
    "upload" to Icons.Outlined.Upload,

    // Time & Calendar
    "schedule" to Icons.Outlined.Schedule,
    "today" to Icons.Outlined.Today,
    "date" to Icons.Outlined.DateRange,
    "alarm" to Icons.Outlined.Alarm,
    "history" to Icons.Outlined.History,
    "update" to Icons.Outlined.Update,
    "timer" to Icons.Outlined.Timer,

    // Actions & UI
    "search" to Icons.Outlined.Search,
    "edit" to Icons.Outlined.Edit,
    "delete" to Icons.Outlined.Delete,
    "delete_forever" to Icons.Outlined.DeleteForever,
    "done" to Icons.Outlined.Done,
    "info" to Icons.Outlined.Info,
    "help" to Icons.Outlined.Help,
    "filter" to Icons.Outlined.FilterAlt,
    "sort" to Icons.Outlined.Sort,
    "refresh" to Icons.Outlined.Refresh,
    "open_new" to Icons.Outlined.OpenInNew,
    "add_box" to Icons.Outlined.AddBox,
    "assignment" to Icons.Outlined.Assignment,
    "dashboard" to Icons.Outlined.Dashboard,
    "timeline" to Icons.Outlined.Timeline,
    "visibility" to Icons.Outlined.Visibility,
    "tune" to Icons.Outlined.Tune,
    "extension" to Icons.Outlined.Extension,

    // Sports & Activities
    "sports" to Icons.Outlined.Sports,
    "golf" to Icons.Outlined.GolfCourse,
    "pool" to Icons.Outlined.Pool,
    "tennis" to Icons.Outlined.SportsTennis,
    "football" to Icons.Outlined.SportsFootball,
    "basketball" to Icons.Outlined.SportsBasketball,
    "skiing" to Icons.Outlined.DownhillSkiing,
    "snowboard" to Icons.Outlined.Snowboarding,
    "kayak" to Icons.Outlined.Kayaking,
    "hiking" to Icons.Outlined.Hiking,
    "biking" to Icons.Outlined.PedalBike,
    "rowing" to Icons.Outlined.Rowing,
    "surfing" to Icons.Outlined.Surfing,
    "paragliding" to Icons.Outlined.Paragliding,
    "self_improvement" to Icons.Outlined.SelfImprovement,
    "hot_tub" to Icons.Outlined.HotTub,

    // Entertainment & Media
    "movie" to Icons.Outlined.Movie,
    "radio" to Icons.Outlined.Radio,
    "videocam" to Icons.Outlined.Videocam,
    "photo" to Icons.Outlined.Photo,
    "photo_library" to Icons.Outlined.PhotoLibrary,
    "slideshow" to Icons.Outlined.Slideshow,
    "podcasts" to Icons.Outlined.Podcasts,
    "piano" to Icons.Outlined.Piano,

    // Travel & Accommodation
    "hotel" to Icons.Outlined.Hotel,
    "luggage" to Icons.Outlined.Luggage,
    "museum" to Icons.Outlined.Museum,

    // Weather & Nature
    "umbrella" to Icons.Outlined.Umbrella,
    "nightlight" to Icons.Outlined.Nightlight,
    "sunny" to Icons.Outlined.LightMode,
    "water" to Icons.Outlined.Water,
    "air" to Icons.Outlined.Air,
    "recycling" to Icons.Outlined.Recycling,

    // Business & Analytics
    "business" to Icons.Outlined.Business,
    "analytics" to Icons.Outlined.Analytics,
    "bar_chart" to Icons.Outlined.BarChart,
    "pie_chart" to Icons.Outlined.PieChart,
    "trending_up" to Icons.Outlined.TrendingUp,
    "trending_down" to Icons.Outlined.TrendingDown,
    "public" to Icons.Outlined.Public,
    "language" to Icons.Outlined.Language,
    "handshake" to Icons.Outlined.Handshake,
    "recommend" to Icons.Outlined.Recommend,

    // Safety & Security
    "verified" to Icons.Outlined.Verified,
    "shield" to Icons.Outlined.Shield,
    "security" to Icons.Outlined.Security,

    // Agriculture & Outdoor
    "agriculture" to Icons.Outlined.Agriculture,

    // Misc & Celebration
    "celebration" to Icons.Outlined.Celebration,
    "rocket" to Icons.Outlined.RocketLaunch,
    "satellite" to Icons.Outlined.SatelliteAlt,
    "notification" to Icons.Outlined.Notifications,
    "scale" to Icons.Outlined.Scale,
    "child_care" to Icons.Outlined.ChildCare,
    "family" to Icons.Outlined.FamilyRestroom,
    "draw" to Icons.Outlined.Draw,
    "castle" to Icons.Outlined.Castle,
    "stadium" to Icons.Outlined.Stadium,
    "church" to Icons.Outlined.Church,
    "gas_station" to Icons.Outlined.LocalGasStation,
    "hospital" to Icons.Outlined.LocalHospital,
    "pharmacy" to Icons.Outlined.LocalPharmacy,
    "pizza" to Icons.Outlined.LocalPizza,
    "laundry" to Icons.Outlined.LocalLaundryService,
    "library" to Icons.Outlined.LocalLibrary,
    "mall" to Icons.Outlined.LocalMall,
    "shipping" to Icons.Outlined.LocalShipping,
    "flashlight" to Icons.Outlined.FlashlightOn,
    "color_lens" to Icons.Outlined.ColorLens,
    "list" to Icons.Outlined.List,
    "table_chart" to Icons.Outlined.TableChart,
    "account_tree" to Icons.Outlined.AccountTree,
    "auto_stories" to Icons.Outlined.AutoStories,
    "receipt_long" to Icons.Outlined.ReceiptLong,
    "price_check" to Icons.Outlined.PriceCheck,
    "inventory" to Icons.Outlined.Inventory,
    "manage_accounts" to Icons.Outlined.ManageAccounts,
    "night_shelter" to Icons.Outlined.NightShelter,
    "mosque" to Icons.Outlined.Mosque,
    "synagogue" to Icons.Outlined.Synagogue,
    "coffee_maker" to Icons.Outlined.CoffeeMaker,
    "set_meal" to Icons.Outlined.SetMeal,
)

private val TAG_ICON_MAP: Map<String, ImageVector> = ALL_MATERIAL_ICONS.toMap()

/** Resolve a stored tag icon key to a vector, or null if unset/unknown. */
fun tagIcon(key: String?): ImageVector? =
    key?.takeIf { it.isNotBlank() }?.let { TAG_ICON_MAP[it] }
